topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 1
    memory: 2400

jobs:
  fedora-27/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f27
          name: freeipa/ci-master-f27
          version: 1.0.3
        timeout: 1800
        topology: *build

  fedora-27/xmlrpc_tests_py2:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest2
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_xmlrpc/
        template: *ci-master-f27
        timeout: 3600
        topology: *ipaserver
        xmlrpc: True

  fedora-27/xmlrpc_tests_py3:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest3
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_xmlrpc/
        template: *ci-master-f27
        timeout: 3600
        topology: *ipaserver
        xmlrpc: True
