topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 5750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 6700
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 1
    memory: 2400

jobs:
  fedora-27/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f27
          name: freeipa/ci-master-f27
          version: 1.0.3
        timeout: 1800
        topology: *build

  fedora-27/webui_tests:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_webui/
        template: *ci-master-f27
        timeout: 8000
        topology: *ipaserver
