topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 1
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 5750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 6700

jobs:
  fedora-28/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f28
          name: freeipa/ci-master-f28
          version: 0.1.5
        timeout: 1800
        topology: *build

  fedora-28/test_webui_g_to_m:
    requires: [fedora-28/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-28/build_url}'
        test_suite: test_webui/test_group.py test_webui/test_hbac.py test_webui/test_host.py test_webui/test_hostgroup.py test_webui/test_idviews.py test_webui/test_krbtpolicy.py test_webui/test_misc_cases.py
        template: *ci-master-f28
        timeout: 7200
        topology: *ipaserver

  fedora-28/test_webui_n_to_r:
    requires: [fedora-28/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{fedora-28/build_url}'
        test_suite: test_webui/test_navigation.py test_webui/test_netgroup.py test_webui/test_pwpolicy.py test_webui/test_range.py test_webui/test_rbac.py test_webui/test_realmdomains.py
        template: *ci-master-f28
        timeout: 7200
        topology: *ipaserver
